CMDS=(
./_output/bin/stitching/2_features_finding
./_output/bin/stitching/2_features_finding2
./_output/bin/stitching/3_images_matching
./_output/bin/stitching/4_rotation_estimation
./_output/bin/stitching/5_images_warping
./_output/bin/stitching/6_exposure_compensation
./_output/bin/stitching/7_seam_estimation
./_output/bin/stitching/8_image_blenders
)
